const quizData = {
    temel: [
        { q: "Bilgisayar ağı (network) nedir?", o: ["İki ya da daha çok bilgisayarın birbirine bağlanması", "Tek bir bilgisayarın internete bağlanması", "Yazıcının bilgisayara bağlanması", "Modem kurulumu"], a: 0, d: "easy", exp: "İki ya da daha çok bilgisayarın birbirine bağlanmasına bilgisayar ağı (network) denir." },
        { q: "Windows'ta eşler arası ağlar ne olarak bilinir?", o: ["Domain", "Workgroup (Çalışma Grubu)", "Server", "Client"], a: 1, d: "easy", exp: "Windows ortamında eşler arası ağlar çalışma grubu (workgroup) olarak bilinir." },
        { q: "Sunucu temelli ağlar Windows'ta ne olarak adlandırılır?", o: ["Workgroup", "Peer-to-peer", "Domain (Etki Alanı)", "LAN"], a: 2, d: "easy", exp: "Sunucu temelli olan ağlar etki alanı (domain) olarak bilinir." },
        { q: "Her ağ adaptörünün sahip olduğu benzersiz adres nedir?", o: ["IP adresi", "MAC adresi", "DNS adresi", "Gateway adresi"], a: 1, d: "easy", exp: "Her ağ adaptörü tek bir MAC adresine sahiptir. Bu adres üretim sırasında kaydedilir ve dünyada eşi yoktur." },
        { q: "Ağ kartının temel görevi nedir?", o: ["Veri depolamak", "Ağa bağlanarak veri iletişimi sağlamak", "Ekran görüntüsü oluşturmak", "Ses çıkışı sağlamak"], a: 1, d: "medium", exp: "Ağ kartı, bilgisayarların ağa bağlanarak veri iletişimi yapabilmelerini sağlayan donanım birimleridir." },
        { q: "Bilgisayar, gelen veri paketinin kendisine ait olup olmadığını nasıl anlar?", o: ["IP adresi ile", "MAC adresi ile", "Dosya adı ile", "Port numarası ile"], a: 1, d: "medium", exp: "Bilgisayarlar ağ üzerinden kendilerine ulaşan veri paketinin kendilerine gelip gelmediğini MAC adresi ile anlarlar." },
        { q: "MAC adresi ne zaman belirlenir?", o: ["İlk açılışta", "Ağa bağlanınca", "Üretim sırasında", "Kullanıcı tarafından"], a: 2, d: "medium", exp: "Her ağ kartı içinde üretilirken kaydedilmiş ve dünyada bir eşi olmayan bir MAC adresi bulunur." },
        { q: "Ağ kartı hangi isimle de bilinir?", o: ["GPU", "Ethernet kartı", "Sound card", "RAM"], a: 1, d: "medium", exp: "Ağ kartı, Ethernet kartı olarak da bilinir ve bilgisayarların ağa bağlanmasını sağlar." },
        { q: "Evdeki iki bilgisayarı birbirine bağlamak için ne kullanılabilir?", o: ["Sadece router", "Switch ve Hub zorunlu", "Çapraz-kros (crossover) kablo", "Fiber optik kablo"], a: 2, d: "hard", exp: "Evdeki iki bilgisayarı birbirine bağlamak için Switch ve Hub kullanmaya gerek yoktur, çapraz-kros (crossover) kablo ile bağlantı yapılabilir." },
        { q: "Ağın büyüklüğü belirlenirken nelere dikkat edilir?", o: ["Sadece kablo uzunluğu", "Bilgisayar sayısı ve Hub port sayısı", "Sadece internet hızı", "Monitör boyutu"], a: 1, d: "hard", exp: "Ağın büyüklüğü: Ağa bağlanacak bilgisayar sayısı ve Hub'ın port sayısının belirlenmesi gerekir." },
        { q: "Web sunucu hizmeti verilecekse ağ tasarımında ne önemlidir?", o: ["Monitör kalitesi", "Ağın çalışma zamanı ve donanım seçimi", "Klavye türü", "Mouse hassasiyeti"], a: 1, d: "hard", exp: "Ağın çalışma zamanı: Ağın günün belirli zaman aralıklarında mı yoksa sürekli mi çalışacağı - web sunucu hizmeti verilecekse buna göre donanım seçilmelidir." },
        { q: "Ağ kartı ve Hub/Switch arasında hangi uyum önemlidir?", o: ["Renk uyumu", "Hız uyumu", "Marka uyumu", "Boyut uyumu"], a: 1, d: "hard", exp: "Cihaz özellikleri: Ağ kartı ve Hub/Switch gibi cihazların hız olarak uyumlu olması gerekir." }
    ],
    topoloji: [
        { q: "BUS ağ topolojisinde aynı anda kaç bilgisayar veri gönderebilir?", o: ["İki", "Üç", "Sadece bir", "Sınırsız"], a: 2, d: "easy", exp: "BUS topolojisinde hat üzerinden aynı anda sadece bir bilgisayar veri gönderebilir." },
        { q: "Günümüzde en yaygın kullanılan ağ topolojisi hangisidir?", o: ["BUS", "Ring", "Yıldız", "Mesh"], a: 2, d: "easy", exp: "Yıldız topoloji günümüzde geçerli olan ağ topolojisidir." },
        { q: "Yıldız topolojisinde merkezi bağlantı aygıtı genellikle nedir?", o: ["Modem", "Switch veya Hub", "Yazıcı", "Monitor"], a: 1, d: "easy", exp: "Bu merkezi bağlantı aygıtı genellikle bir switch ya da hub olmaktadır." },
        { q: "BUS topolojisinde kablonun sonunda ne olmalıdır?", o: ["Switch", "Hub", "Sonlandırıcı (Terminator)", "Router"], a: 2, d: "medium", exp: "BUS topolojisinde kablonun sonunda sonlandırıcı (Terminator) olmalıdır." },
        { q: "Ring topolojisinde sinyallerin dolaşımını kontrol eden nedir?", o: ["Token (Jeton)", "MAC adresi", "IP adresi", "DNS"], a: 0, d: "medium", exp: "Sinyallerin dolaşımını kontrol etmek için jeton (token) adı verilen bir bilgi kullanılır." },
        { q: "Mesh topolojisinde her bilgisayar diğerlerine nasıl bağlıdır?", o: ["Merkezi hub üzerinden", "Direkt bağlı", "Kablosuz sadece", "Hiç bağlı değil"], a: 1, d: "medium", exp: "Mesh yani örgü topolojisinde her bilgisayar ağdaki diğer bilgisayara direkt bağlıdır." },
        { q: "Yıldız topolojisinde kablo maksimum kaç metre olabilir?", o: ["50 metre", "100 metre", "200 metre", "500 metre"], a: 1, d: "medium", exp: "Yıldız topolojisinde kablo 100 metreyi geçerse çalışmaz." },
        { q: "BUS topolojisinin dezavantajı nedir?", o: ["Çok pahalı", "Hattın bir yerinde kopukluk tüm ağı etkiler", "Kurulumu zor", "Yavaş"], a: 1, d: "hard", exp: "Dezavantajları ise hattın belli bir yerinde kopukluk olduğu zaman tüm ağın etkilenmesidir." },
        { q: "Ring topolojisinde bir bilgisayar arızalanırsa ne olur?", o: ["Sadece o bilgisayar etkilenir", "Bütün ağ çöker", "Hiçbir şey olmaz", "Hız artar"], a: 1, d: "hard", exp: "Halkada yer alan bir bilgisayarın arızalanması bütün ağın çökmesi anlamına gelir." },
        { q: "Ağaç topolojisinde omurga kablosu bozulursa ne olur?", o: ["Hiçbir şey olmaz", "Sadece bir segment etkilenir", "Bölümlerdeki ağ trafiği etkilenir", "Hız artar"], a: 2, d: "hard", exp: "Omurga kablosu bozulduğunda bölümlerdeki ağ trafiği etkilenir." },
        { q: "Mesh topolojisi en çok hangi ağlarda tercih edilir?", o: ["Kablolu ağlar", "Kablosuz ağlar", "Fiber ağlar", "Koaksiyel ağlar"], a: 1, d: "hard", exp: "Örgü topolojisi, yaygın olarak kablosuz ağlarda tercih edilen bir topolojidir." },
        { q: "Yıldız topolojisinde hub veya switch arızalanırsa ne olur?", o: ["Sadece bir PC etkilenir", "Hiçbir şey olmaz", "Tüm ağ çöker", "Hız düşer"], a: 2, d: "hard", exp: "Hub veya switch arızalanırsa komple gider - tüm ağ etkilenir." }
    ],
    kablo: [
        { q: "UTP kablonun açılımı nedir?", o: ["Unshielded Twisted Pair", "Ultra Thin Port", "Universal Transfer Protocol", "United Tech Power"], a: 0, d: "easy", exp: "UTP = UnShielded Twisted Pair (Korumasız Bükümlü Çift Kablo)" },
        { q: "TP kablolar arasında en yaygın kullanılan hangisidir?", o: ["STP", "UTP", "FSTP", "Koaksiyel"], a: 1, d: "easy", exp: "UTP en yaygın kullanılan kablo türüdür. Çünkü TP kablolar arasında en ucuz olanıdır." },
        { q: "Sarmal çift ağ kabloları bir kılıfın içinde kaç çift ince kablodan oluşur?", o: ["2 çift", "4 çift", "6 çift", "8 çift"], a: 1, d: "easy", exp: "Sarmal çift ağ kabloları, bir kılıfın içindeki 4 çift ince kablodan oluşur." },
        { q: "CAT 5 kablonun hızı nedir?", o: ["10 Mbit/s", "100 Mbit/s", "1 Gbit/s", "10 Gbit/s"], a: 1, d: "medium", exp: "CAT 5 kablo 100 Mbit/s hız ve 100 MHz frekans destekler." },
        { q: "CAT 5E kablonun hızı nedir?", o: ["100 Mbit/s", "1 Gbit/s", "10 Gbit/s", "100 Gbit/s"], a: 1, d: "medium", exp: "CAT 5E kablo 1 Gbit/s hız ve 100 MHz frekans destekler." },
        { q: "Koaksiyel kablo hangi topolojide yaygın kullanılır?", o: ["Yıldız", "Ring", "Linear BUS", "Mesh"], a: 2, d: "medium", exp: "Bilgisayar ağlarında koaksiyel kablo yaygın olarak linear bus topolojilerde kullanılır." },
        { q: "Token Ring'de UTP kablo kullanıldığında maksimum kaç bilgisayar bağlanabilir?", o: ["36", "72", "144", "260"], a: 1, d: "hard", exp: "IBM token ring'de maksimum bilgisayar sayısı UTP kabloda 72'dir." },
        { q: "Token Ring'de STP kablo kullanıldığında maksimum kaç bilgisayar bağlanabilir?", o: ["72", "144", "260", "500"], a: 2, d: "hard", exp: "IBM token ring'de maksimum bilgisayar sayısı STP kabloda 260'tır." },
        { q: "CAT 7A kablonun maksimum hızı nedir?", o: ["10 Gbit/s", "40 Gbit/s", "100 Gbit/s", "1 Tbit/s"], a: 2, d: "hard", exp: "CAT 7A kablo 100 Gbit/s hız ve 1 GHz frekans destekler." },
        { q: "Sarmal sayısı arttıkça ne olur?", o: ["Hız düşer maliyet düşer", "Hız artar maliyet artar", "Hız düşer maliyet artar", "Değişmez"], a: 1, d: "hard", exp: "Sarmal sayısı arttıkça veri iletişim hızı ve kablo maliyeti artar." },
        { q: "TP kabloların kaç türü mevcuttur?", o: ["2 tür", "3 tür", "4 tür", "5 tür"], a: 1, d: "medium", exp: "TP kabloların STP, UTP ve FSTP olmak üzere 3 türü mevcuttur." },
        { q: "CAT 6 kablonun frekansı nedir?", o: ["100 MHz", "250 MHz", "500 MHz", "1 GHz"], a: 1, d: "hard", exp: "CAT 6 kablo 1 Gbit/s hız ve 250 MHz frekans destekler." }
    ],
    ieee: [
        { q: "IEEE 802.11 hangi teknolojiyi tanımlar?", o: ["Ethernet", "Token Ring", "WiFi (Kablosuz LAN)", "Bluetooth"], a: 2, d: "easy", exp: "IEEE 802.11 Kablosuz LAN-Mesh (WiFi) standardıdır." },
        { q: "IEEE 802.3 hangi teknolojiyi tanımlar?", o: ["Ethernet", "Token Ring", "WiFi", "Bluetooth"], a: 0, d: "easy", exp: "IEEE 802.3 Ethernet standardıdır." },
        { q: "WiFi ne anlama gelir?", o: ["Wide Fidelity", "Wireless Fidelity", "Wired Fiber", "Web Interface"], a: 1, d: "easy", exp: "Kablosuz LAN bağlantısı, WiFi (Wireless Fidelity) olarak da adlandırılır." },
        { q: "IEEE 802.15.1 hangi teknolojiyi tanımlar?", o: ["WiFi", "WiMax", "Bluetooth", "Ethernet"], a: 2, d: "medium", exp: "IEEE 802.15.1 Bluetooth Sertifikasyon standardıdır." },
        { q: "IEEE 802.16 hangi teknolojiyi tanımlar?", o: ["Bluetooth", "WiFi", "WiMax", "Token Ring"], a: 2, d: "medium", exp: "IEEE 802.16 Genişbant Kablosuz-WiMax standardıdır." },
        { q: "WLAN'da veri iletimi için ne kullanılır?", o: ["Bakır kablo", "Fiber optik", "Radyo dalgaları", "Koaksiyel kablo"], a: 2, d: "medium", exp: "WLAN'da veri iletimi için radyo dalgaları kullanılır." },
        { q: "IEEE 802.5 hangi teknolojiyi tanımlar?", o: ["Ethernet", "Token Ring", "WiFi", "Fiber Optik"], a: 1, d: "medium", exp: "IEEE 802.5 Token Ring standardıdır." },
        { q: "WAP kendisine bağlı kablosuz kullanıcılar için ne gibi davranır?", o: ["Router", "Hub", "Switch", "Modem"], a: 1, d: "hard", exp: "WAP, kendisine bağlı kablosuz kullanıcılar için hub gibi davranır." },
        { q: "Kablosuz LAN, kablolu LAN'a göre nasıldır?", o: ["Daha hızlı", "Aynı hızda", "Daha yavaş", "Karşılaştırılamaz"], a: 2, d: "hard", exp: "Kesin olan, kablosuz LAN'ın kablolu LAN standartlarına göre yavaş olduğudur." },
        { q: "IEEE 802.8 hangi teknolojiyi tanımlar?", o: ["Ethernet", "Fiber Optik TAG", "WiFi", "Bluetooth"], a: 1, d: "hard", exp: "IEEE 802.8 Fiber Optik TAG standardıdır." },
        { q: "IEEE 802.4 hangi teknolojiyi tanımlar?", o: ["Token Bus", "Token Ring", "Ethernet", "WiFi"], a: 0, d: "hard", exp: "IEEE 802.4 Token Bus standardıdır." },
        { q: "IEEE 802.14 hangi teknolojiyi tanımlar?", o: ["WiFi", "Kablo Modemler", "Bluetooth", "WiMax"], a: 1, d: "hard", exp: "IEEE 802.14 Kablo Modemler standardıdır." }
    ],
    cihaz: [
        { q: "Yineleyici (Repeater) ne işe yarar?", o: ["Veri depolar", "Sinyali güçlendirir", "IP atar", "Veri şifreler"], a: 1, d: "easy", exp: "Yineleyici, kablonun kapasitesinden daha fazla mesafelere bağlantı kurulması gerektiğinde araya bir yükseltici konularak sinyalin güçlendirilmesini sağlayan cihazdır." },
        { q: "Router (Yönlendirici) ne sağlar?", o: ["Sinyal güçlendirme", "Ağlar arası haberleşme bağlantısı", "Veri depolama", "Ekran çıkışı"], a: 1, d: "easy", exp: "Yönlendirici, ağlar arası (LAN-LAN, LAN-WAN, WAN-WAN) haberleşmenin yapılabilmesi için ara bağlantıyı sağlar." },
        { q: "Köprü (Bridge) ne için kullanılır?", o: ["Sinyal güçlendirme", "Bağımsız ağları birbirine bağlama", "IP adresi atama", "Veri şifreleme"], a: 1, d: "easy", exp: "Köprü, birbirinden bağımsız ağları birbirine bağlamak için kullanılır." },
        { q: "Yıldız topolojisinde merkezi cihaz hangisidir?", o: ["Router", "Modem", "Hub veya Switch", "Repeater"], a: 2, d: "medium", exp: "Yıldız topolojisinde merkezi bağlantı aygıtı genellikle bir switch ya da hub olmaktadır." },
        { q: "Router hangi tür ağları bağlayabilir?", o: ["Sadece LAN-LAN", "LAN-LAN, LAN-WAN, WAN-WAN", "Sadece WAN-WAN", "Sadece kablosuz"], a: 1, d: "medium", exp: "Router, LAN-LAN, LAN-WAN, WAN-WAN ağlar arası haberleşmeyi sağlar." },
        { q: "Köprü ile hangi topolojideki ağlar birbirine bağlanabilir?", o: ["Sadece aynı topoloji", "Farklı topolojiler de olabilir", "Sadece yıldız", "Sadece mesh"], a: 1, d: "medium", exp: "Bağlanacak ağlar birbiri ile aynı topolojide veya farklı topolojide olabilir." },
        { q: "Bilgisayarlar arası mesafe çok uzunsa ne kullanılmalı?", o: ["Daha kalın kablo", "Tekrarlayıcı (Repeater)", "Daha fazla hub", "Kablosuz"], a: 1, d: "medium", exp: "Bilgisayarlar arası mesafe çok uzun ise tekrarlayıcı (repeater) kullanılması gerekir." },
        { q: "Yıldız topolojisinde kaç switch/hub kullanılabilir?", o: ["Sadece 1", "Maksimum 2", "Birden fazla", "Hiç kullanılmaz"], a: 2, d: "hard", exp: "Yıldız topolojisinde BİRDEN FAZLA SWİTCH VE HUB KULLANILIR." },
        { q: "Hub arızalanırsa yıldız topolojisinde ne olur?", o: ["Sadece bir PC etkilenir", "Ağ yavaşlar", "Tüm ağ çöker", "Hiçbir şey olmaz"], a: 2, d: "hard", exp: "Hub veya switch arızalanırsa komple gider - yani tüm ağ etkilenir." },
        { q: "Repeater ne zaman gereklidir?", o: ["Her zaman", "Kablonun kapasitesinden fazla mesafe için", "Güvenlik için", "Hız için"], a: 1, d: "hard", exp: "Kablonun kapasitesinden daha fazla mesafelere bağlantı kurulması gerektiğinde repeater kullanılır." },
        { q: "Switch ve Hub arasındaki önemli fark nedir?", o: ["Hub daha pahalı", "Switch daha akıllı yönlendirme yapar", "Aynı cihaz", "Hub kablosuz"], a: 1, d: "hard", exp: "Switch, Hub'a göre daha akıllı çalışır ve veriyi sadece hedef porta yönlendirir." },
        { q: "WAP (Wireless Access Point) hangi cihaz gibi davranır?", o: ["Router", "Switch", "Hub", "Modem"], a: 2, d: "hard", exp: "WAP, kendisine bağlı kablosuz kullanıcılar için hub gibi davranır." }
    ],
    ip: [
        { q: "IPv4 adresi toplamda kaç bittir?", o: ["16 bit", "32 bit", "64 bit", "128 bit"], a: 1, d: "easy", exp: "IPv4 adresi toplam 32 bit ve noktalarla ayrılmış 4 adet 8 bitlik sayıdan oluşur." },
        { q: "IPv4 adresi kaç adet 8 bitlik sayıdan oluşur?", o: ["2", "3", "4", "5"], a: 2, d: "easy", exp: "IPv4 adresi noktalarla ayrılmış 4 adet 8 bitlik sayıdan oluşur." },
        { q: "Günümüzde yaygın olarak hangi IP versiyonu kullanılır?", o: ["IPv2", "IPv4", "IPv6", "IPv8"], a: 1, d: "easy", exp: "Yaygın olarak IPv4 adresler kullanılıyor." },
        { q: "IP adresinin prefix kısmı neyi belirtir?", o: ["Bilgisayar adresini", "Ağın fiziksel adresini", "Port numarasını", "MAC adresini"], a: 1, d: "medium", exp: "IP adresinin prefix kısmı bir bilgisayarın bağlı bulunduğu ağın fiziksel adresidir." },
        { q: "IP adresinin suffix kısmı neyi belirtir?", o: ["Ağ adresi", "Bilgisayarı diğerlerinden ayıran kısım", "Gateway", "DNS sunucu"], a: 1, d: "medium", exp: "IP adresinin suffix kısmı bir ağ içinde bir bilgisayarı diğerlerinden ayıran kısımdır." },
        { q: "IPv4 adresinde her bir oktet kaç bittir?", o: ["4 bit", "8 bit", "16 bit", "32 bit"], a: 1, d: "medium", exp: "IPv4 adresi 4 adet 8 bitlik (oktet) sayıdan oluşur." },
        { q: "192.168.1.5 adresinde '192.168.1' kısmı neyi temsil eder?", o: ["Suffix", "Port", "Prefix (Ağ adresi)", "MAC"], a: 2, d: "medium", exp: "IP adresinin prefix kısmı ağın adresini belirtir." },
        { q: "IPv4'te maksimum değer bir oktette kaçtır?", o: ["127", "255", "512", "1024"], a: 1, d: "hard", exp: "8 bit ile maksimum 255 (2^8 - 1) değeri gösterilebilir." },
        { q: "IPv4 ile teorik olarak kaç adres tanımlanabilir?", o: ["2^16", "2^32", "2^64", "2^128"], a: 1, d: "hard", exp: "32 bit ile 2^32 (yaklaşık 4.3 milyar) adres tanımlanabilir." },
        { q: "Aynı ağdaki iki bilgisayarın IP adresinde ne aynı olmalıdır?", o: ["Suffix", "Prefix", "Tüm adres", "Hiçbiri"], a: 1, d: "hard", exp: "Aynı ağdaki bilgisayarların prefix (ağ) kısmı aynı olmalıdır." },
        { q: "IP adresi hangi katmanda çalışır?", o: ["Fiziksel", "Veri bağlantı", "Ağ", "Uygulama"], a: 2, d: "hard", exp: "IP adresi OSI modelinin Ağ (Network) katmanında çalışır." },
        { q: "Prefix ve Suffix ayrımı ne ile belirlenir?", o: ["MAC adresi", "Alt ağ maskesi (Subnet mask)", "Gateway", "DNS"], a: 1, d: "hard", exp: "IP adresinde hangi kısmın prefix, hangi kısmın suffix olduğu alt ağ maskesi (subnet mask) ile belirlenir." }
    ]
};
